import "@/styles/globals.css";
import type { Metadata } from "next";
import Providers from "./providers";
import fonts from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        suppressHydrationWarning={true}
        className={`${fonts.variable} bg-gray-100 text-base dark:bg-neutral-900 text-neutral-900 dark:text-neutral-200 font-yekanbakh antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
